<a href="https://colab.research.google.com/github/DarK-ML/FrozenLake/blob/master/FrozenLake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

env = gym.make("FrozenLake-v0")

action_size = env.action_space.n
state_size = env.observation_space.n
q_table = np.zeros((state_size, action_size))

In [0]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
num_episodes = 10000
max_steps_per_episode = 100
learning_rate = 0.1
discount_rate = 0.99
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [0]:
rewards_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
             learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        state = new_state
        rewards_current_episode += reward 
        if done == True: 
            break
    exploration_rate = min_exploration_rate + \
       (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)





In [0]:
# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)


********Average reward per thousand episodes********

1000 :  0.05200000000000004
2000 :  0.21100000000000016
3000 :  0.4310000000000003
4000 :  0.5560000000000004
5000 :  0.6100000000000004
6000 :  0.6780000000000005
7000 :  0.6940000000000005
8000 :  0.6600000000000005
9000 :  0.6990000000000005
10000 :  0.6760000000000005


********Q-table********

[[0.53469274 0.51358941 0.51960043 0.52074033]
 [0.44863903 0.31519838 0.35628077 0.52428228]
 [0.40160822 0.43210275 0.39916813 0.47925701]
 [0.26559566 0.31368232 0.26289591 0.453912  ]
 [0.55805124 0.34312946 0.37712853 0.1775248 ]
 [0.         0.         0.         0.        ]
 [0.19655723 0.12327127 0.28506888 0.07455797]
 [0.         0.         0.         0.        ]
 [0.35235899 0.39345084 0.34701063 0.58017749]
 [0.31131648 0.64223886 0.49479964 0.38336465]
 [0.53997251 0.41841804 0.47105895 0.31102145]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.48448801 0.55679335 0.77808297 

In [0]:
for episode in range(2):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(1)
        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break
        state = new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
